/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as BookedRouteImport } from './routes/booked'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as FitCheckRouteImport } from './routes/fit-check'
import { Route as MakeRoomRouteImport } from './routes/make-room'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as WhatIOfferRouteImport } from './routes/what-i-offer'
import { Route as WhoItsForRouteImport } from './routes/who-its-for'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as DemoCoachRouteImport } from './routes/demo.coach'
import { Route as ManageTokenRouteImport } from './routes/manage.$token'
import { Route as ApiPublicHooksDigestRouteImport } from './routes/api/public/hooks/digest'
import { Route as ApiPublicHooksTickRouteImport } from './routes/api/public/hooks/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BookedRoute = BookedRouteImport.update({
  id: '/booked',
  path: '/booked',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const FitCheckRoute = FitCheckRouteImport.update({
  id: '/fit-check',
  path: '/fit-check',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeRoomRoute = MakeRoomRouteImport.update({
  id: '/make-room',
  path: '/make-room',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIOfferRoute = WhatIOfferRouteImport.update({
  id: '/what-i-offer',
  path: '/what-i-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoItsForRoute = WhoItsForRouteImport.update({
  id: '/who-its-for',
  path: '/who-its-for',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DemoCoachRoute = DemoCoachRouteImport.update({
  id: '/demo/coach',
  path: '/demo/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageTokenRoute = ManageTokenRouteImport.update({
  id: '/manage/$token',
  path: '/manage/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDigestRoute = ApiPublicHooksDigestRouteImport.update({
  id: '/api/public/hooks/digest',
  path: '/api/public/hooks/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTickRoute = ApiPublicHooksTickRouteImport.update({
  id: '/api/public/hooks/tick',
  path: '/api/public/hooks/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/booked': typeof BookedRoute
  '/emails': typeof EmailsRoute
  '/fit-check': typeof FitCheckRoute
  '/make-room': typeof MakeRoomRoute
  '/prices': typeof PricesRoute
  '/privacy': typeof PrivacyRoute
  '/what-i-offer': typeof WhatIOfferRoute
  '/who-its-for': typeof WhoItsForRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/demo/coach': typeof DemoCoachRoute
  '/manage/$token': typeof ManageTokenRoute
  '/api/public/hooks/digest': typeof ApiPublicHooksDigestRoute
  '/api/public/hooks/tick': typeof ApiPublicHooksTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/booked': typeof BookedRoute
  '/emails': typeof EmailsRoute
  '/fit-check': typeof FitCheckRoute
  '/make-room': typeof MakeRoomRoute
  '/prices': typeof PricesRoute
  '/privacy': typeof PrivacyRoute
  '/what-i-offer': typeof WhatIOfferRoute
  '/who-its-for': typeof WhoItsForRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/demo/coach': typeof DemoCoachRoute
  '/manage/$token': typeof ManageTokenRoute
  '/api/public/hooks/digest': typeof ApiPublicHooksDigestRoute
  '/api/public/hooks/tick': typeof ApiPublicHooksTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/booked': typeof BookedRoute
  '/emails': typeof EmailsRoute
  '/fit-check': typeof FitCheckRoute
  '/make-room': typeof MakeRoomRoute
  '/prices': typeof PricesRoute
  '/privacy': typeof PrivacyRoute
  '/what-i-offer': typeof WhatIOfferRoute
  '/who-its-for': typeof WhoItsForRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/demo/coach': typeof DemoCoachRoute
  '/manage/$token': typeof ManageTokenRoute
  '/api/public/hooks/digest': typeof ApiPublicHooksDigestRoute
  '/api/public/hooks/tick': typeof ApiPublicHooksTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/booked'
    | '/emails'
    | '/fit-check'
    | '/make-room'
    | '/prices'
    | '/privacy'
    | '/what-i-offer'
    | '/who-its-for'
    | '/coach'
    | '/demo/coach'
    | '/manage/$token'
    | '/api/public/hooks/digest'
    | '/api/public/hooks/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/booked'
    | '/emails'
    | '/fit-check'
    | '/make-room'
    | '/prices'
    | '/privacy'
    | '/what-i-offer'
    | '/who-its-for'
    | '/coach'
    | '/demo/coach'
    | '/manage/$token'
    | '/api/public/hooks/digest'
    | '/api/public/hooks/tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/book'
    | '/booked'
    | '/emails'
    | '/fit-check'
    | '/make-room'
    | '/prices'
    | '/privacy'
    | '/what-i-offer'
    | '/who-its-for'
    | '/_authenticated/coach'
    | '/demo/coach'
    | '/manage/$token'
    | '/api/public/hooks/digest'
    | '/api/public/hooks/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  BookedRoute: typeof BookedRoute
  EmailsRoute: typeof EmailsRoute
  FitCheckRoute: typeof FitCheckRoute
  MakeRoomRoute: typeof MakeRoomRoute
  PricesRoute: typeof PricesRoute
  PrivacyRoute: typeof PrivacyRoute
  WhatIOfferRoute: typeof WhatIOfferRoute
  WhoItsForRoute: typeof WhoItsForRoute
  DemoCoachRoute: typeof DemoCoachRoute
  ManageTokenRoute: typeof ManageTokenRoute
  ApiPublicHooksDigestRoute: typeof ApiPublicHooksDigestRoute
  ApiPublicHooksTickRoute: typeof ApiPublicHooksTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booked': {
      id: '/booked'
      path: '/booked'
      fullPath: '/booked'
      preLoaderRoute: typeof BookedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fit-check': {
      id: '/fit-check'
      path: '/fit-check'
      fullPath: '/fit-check'
      preLoaderRoute: typeof FitCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make-room': {
      id: '/make-room'
      path: '/make-room'
      fullPath: '/make-room'
      preLoaderRoute: typeof MakeRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-i-offer': {
      id: '/what-i-offer'
      path: '/what-i-offer'
      fullPath: '/what-i-offer'
      preLoaderRoute: typeof WhatIOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-its-for': {
      id: '/who-its-for'
      path: '/who-its-for'
      fullPath: '/who-its-for'
      preLoaderRoute: typeof WhoItsForRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/demo/coach': {
      id: '/demo/coach'
      path: '/demo/coach'
      fullPath: '/demo/coach'
      preLoaderRoute: typeof DemoCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$token': {
      id: '/manage/$token'
      path: '/manage/$token'
      fullPath: '/manage/$token'
      preLoaderRoute: typeof ManageTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/digest': {
      id: '/api/public/hooks/digest'
      path: '/api/public/hooks/digest'
      fullPath: '/api/public/hooks/digest'
      preLoaderRoute: typeof ApiPublicHooksDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tick': {
      id: '/api/public/hooks/tick'
      path: '/api/public/hooks/tick'
      fullPath: '/api/public/hooks/tick'
      preLoaderRoute: typeof ApiPublicHooksTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  BookedRoute: BookedRoute,
  EmailsRoute: EmailsRoute,
  FitCheckRoute: FitCheckRoute,
  MakeRoomRoute: MakeRoomRoute,
  PricesRoute: PricesRoute,
  PrivacyRoute: PrivacyRoute,
  WhatIOfferRoute: WhatIOfferRoute,
  WhoItsForRoute: WhoItsForRoute,
  DemoCoachRoute: DemoCoachRoute,
  ManageTokenRoute: ManageTokenRoute,
  ApiPublicHooksDigestRoute: ApiPublicHooksDigestRoute,
  ApiPublicHooksTickRoute: ApiPublicHooksTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
