/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as BookedRouteImport } from './routes/booked'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as MakeRoomRouteImport } from './routes/make-room'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BookedRoute = BookedRouteImport.update({
  id: '/booked',
  path: '/booked',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeRoomRoute = MakeRoomRouteImport.update({
  id: '/make-room',
  path: '/make-room',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/booked': typeof BookedRoute
  '/emails': typeof EmailsRoute
  '/make-room': typeof MakeRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/booked': typeof BookedRoute
  '/emails': typeof EmailsRoute
  '/make-room': typeof MakeRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/booked': typeof BookedRoute
  '/emails': typeof EmailsRoute
  '/make-room': typeof MakeRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/book' | '/booked' | '/emails' | '/make-room'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book' | '/booked' | '/emails' | '/make-room'
  id: '__root__' | '/' | '/book' | '/booked' | '/emails' | '/make-room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  BookedRoute: typeof BookedRoute
  EmailsRoute: typeof EmailsRoute
  MakeRoomRoute: typeof MakeRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booked': {
      id: '/booked'
      path: '/booked'
      fullPath: '/booked'
      preLoaderRoute: typeof BookedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make-room': {
      id: '/make-room'
      path: '/make-room'
      fullPath: '/make-room'
      preLoaderRoute: typeof MakeRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  BookedRoute: BookedRoute,
  EmailsRoute: EmailsRoute,
  MakeRoomRoute: MakeRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
